Feature im 06 4 einschulungsplanung
fes-wiesbaden/22be10-p3-fesus-gruppe1 pull request #12
Opened 2023-11-09 12:52 UTC by lenav99

Schaut den euch bitte an, ob das so passt.

2023-11-10 08:03 UTC, thisami approved these changes

2023-11-13 08:01 UTC, VogtJoshua reviewed
Eingesehen und durchgeschaut

2023-11-15 08:18 UTC, lenav99 commented on src/main/java/com/fes/hazelnut/schoolnut/data/entity/config/ConfigServiceImpl.java
> +     * Persist a configuration to the database and flush
Persists

2023-11-15 08:28 UTC, tilokowalski requested changes
Abgesehen von den einzelnen Kommentaren fällt die Javadocformatierung etwas aus dem Muster und enthält stellenweise ein paar kleinere Fehler

2023-11-15 08:28 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/modal/EnrollmentPlanerModal.java
> +    private ConfigService configService;
Injezierte Services sollten final sein, beziehnungsweise wollen wir in ViewComponenten eigentlich die Util Service.get(clazz) nutzen, da das Autowiring hier fehlschlagen könnte wenn der Vaadin Context asynchrin ist

2023-11-15 08:28 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/modal/EnrollmentPlanerModal.java
> +    private DatePicker datePicker = new DatePicker("Einschulungsdatum");
deklarationen die eine direkte initialisierung enthalten auch immer final

2023-11-15 08:28 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/modal/EnrollmentPlanerModal.java
> +    private LocalDate inputDate;
Dieses Attribut kannst du dir sparen da inputDate nur als lokale Variable in saveDate verwendet wird

2023-11-15 08:28 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/modal/EnrollmentPlanerModal.java
> +        headline.getStyle().set("margin", "var(--lumo-space-m) 0 0 0")
Wäre schon wenn wir auf Style Properties verzichten könnten, da das relativ inkonsistent werden könnte. I.d.R. kann man all das über Vaadin Methoden lösen, im "schlimmsten" Fall aber über Klassen statt direkten Style Properties

2023-11-15 08:28 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/modal/EnrollmentPlanerModal.java
> +        headline.getStyle().set("margin", "var(--lumo-space-m) 0 0 0")
Wenn wir tatsächlich custom styling benötigen wäre es gut dieses wirklich in die css dateien auszulagern

2023-11-15 08:28 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/modal/EnrollmentPlanerModal.java
> +        ToastNotification.show("Die Einschulung wurde erfolgreich angelegt", NotificationVariant.LUMO_SUCCESS);
Das Einschulungsdatum wurde erfolgreich aktualisiert

2023-11-15 08:28 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/ClassAdministrationPage.java
> +    final ConfigService configService;
auch hier bietet sich aus Gründen der Konsistenz die Verwendung der Service Klasse an, in Pages ist diese Injection practice aber theoretisch okay

2023-11-15 08:28 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/ClassAdministrationPage.java
>      final SchoolclassService schoolclassService;
hier ist zwar das final vorhanden, dafür fehlt jedoch private

2023-11-15 08:33 UTC, tilokowalski requested changes

2023-11-15 08:33 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/data/entity/enrollment/EnrollmentService.java
> +     * TODO Kommentieren!
ih

2023-11-15 08:33 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/data/entity/enrollment/EnrollmentServiceImpl.java
> +     * TODO Kommentieren!
bah

2023-11-15 08:33 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/data/entity/enrollment/form/EnrollmentFormService.java
> +     * TODO Kommentieren!
puuuh

2023-11-15 08:33 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/data/entity/enrollment/form/EnrollmentFormServiceImpl.java
> +     * TODO Kommentieren!
uff

2023-11-15 08:33 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/data/entity/enrollment/form/EnrollmentFormServiceImpl.java
> +     * TODO Kommentieren!
oh man

2023-11-15 08:33 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/data/entity/enrollment/form/EnrollmentFormServiceImpl.java
> +     * TODO Kommentieren!
ohje

2023-11-15 08:33 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/modal/EnrollmentPlanerModal.java
> +    private ConfigService configService = Service.get(ConfigService.class);
final

2023-11-15 08:33 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/modal/EnrollmentPlanerModal.java
> +        //TODO löschen der enrollment und enrollment form Sachen aus der Datenbank bei Anlegen eines neuen Einschulungsdatums
todo weg

2023-11-15 08:48 UTC, tilokowalski requested changes

2023-11-15 08:48 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/modal/EnrollmentPlanerModal.java
> +
Irgendwo im Dialog noch Hinweis auf Löschung der alten Daten

2023-11-15 09:20 UTC, VogtJoshua approved these changes

2023-11-15 09:38 UTC, closed without merging