Feature im 08 09 klassenliste drucken
fes-wiesbaden/22be10-p3-fesus-gruppe1 pull request #16
Opened 2023-11-16 11:59 UTC by lenav99

Schaut euch das mal bitte an, ob das so passt

2023-11-16 12:18 UTC, thisami approved these changes

2023-11-16 12:18 UTC, thisami commented on src/main/java/com/fes/hazelnut/schoolnut/data/entity/enrollment/form/EnrollmentFormServiceImpl.java
> +@Service
Annotations direkt an die Klasse!?

2023-11-16 12:18 UTC, thisami commented on src/main/java/com/fes/hazelnut/schoolnut/data/entity/enrollment/form/EnrollmentFormServiceImpl.java
> +    @Autowired
gleiche Geschichte

2023-11-17 06:31 UTC, VogtJoshua commented on src/main/java/com/fes/hazelnut/schoolnut/data/entity/enrollment/EnrollmentServiceImpl.java
>       * @return The enrollment.
Würde hier nicht noch ein Kommentar hinkommen wegen dem Attribut Code?

2023-11-17 06:39 UTC, VogtJoshua submitted a review, later dismissed

2023-11-17 07:21 UTC, tilokowalski requested changes

2023-11-17 07:21 UTC, tilokowalski commented on pom.xml
> +
leerzeichen

2023-11-17 07:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/listener/PrintClasslistAction.java
> + * The PDF  is generated using the iText library.
leerzeichen zu viel

2023-11-17 07:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/listener/PrintClasslistAction.java
> +     * @param arg0 The click event triggered by the button.
Leerzeichen zwischen description und tags, besser wäre als benennung für den parameter außerdem "event", sowohl im doc als auch name des parameters

2023-11-17 07:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/listener/PrintClasslistAction.java
> +    public void onComponentEvent(ClickEvent<Button> arg0) {
Bisschen Spaghetti-Code weil alles in einer Methode untereinander steht, ist aber in Ordnung zumal das ja eh abstrahiert werden soll

2023-11-17 07:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/listener/PrintClasslistAction.java
> +                document.add(
Java Formatter / line wrap

2023-11-17 07:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/listener/PrintClasslistAction.java
> +                        new Paragraph("Vorname: " + entry.getEnrollmentForm().getFirstname().toString(), normalFont));
.toString() brauchst du nicht weil firstname ein String ist

2023-11-17 07:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/listener/PrintClasslistAction.java
> +                        new Paragraph("Nachname: " + entry.getEnrollmentForm().getLastname().toString(), normalFont));
hier ist toString() sogar fatal weil lastnames oft nullable sind und toString auf null logischerweise eine NullPointerException werfen würde

2023-11-17 07:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/listener/PrintClasslistAction.java
> +        arg0.getSource().getUI()
formatter

2023-11-17 07:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/listener/PrintClasslistAction.java
> +                .ifPresent(ui -> ui.getPage().executeJs("var a = document.createElement('a'); a.href='" + dataUri +
grausig gelöst, download per javascript irgendwie in den viewport injected - das ist extrem fehleranfällig. Das geht sicherlich auch über Java / Vaadin built in functions

2023-11-17 07:58 UTC, thisami approved these changes

2023-11-17 08:06 UTC, merged