Feature im 07 5 confirmation
fes-wiesbaden/22be10-p3-fesus-gruppe1 pull request #39
Opened 2023-11-22 16:27 UTC by thisami

2023-11-22 16:28 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/frame/allocation/CodeInputFrame.java
> +        textFieldCode.setMaxLength(6);
⚠️ **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.coding.MagicNumberCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'6' is a magic number.

2023-11-22 16:28 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/data/entity/enrollment/EnrollmentEntity.java
> +    @Column(unique = true, nullable = false, length = 6)
⚠️ **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.coding.MagicNumberCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'6' is a magic number.

2023-11-22 16:29 UTC, thisami commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EnrollmentConfirmationDialog.java
> +
@tilokowalski ich bin mir bei den While Schleifen nicht zu 100% sicher, ob die 1. Methode (einkommentiert) funktioniert.

2023-11-22 17:21 UTC, tilokowalski requested changes
ich sage jetzt schonmal: es tut mir leid. Da hat das Bananenweizen etwas aus mir gesprochen als ich die Kommentare geschrieben habe

2023-11-22 17:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EnrollmentConfirmationDialog.java
> +
Würde funktionieren, nur müsstest du dem enrollment auch den Datentypen Optional<EnrollmentEntity> geben, weil der wenn ich das richtig sehe sonst nirgends initialisiert ist. Genau so hätte ich die Schleife tatsächlich auch gelöst, ist sehr nice umgesetzt.

Bei der jetzt einkommentierten Version nutzt du einfach einen Hilfsboolean anstatt direkt auf die Bedingung zu prüfen, die dahinter steckt (enrollment.isPresent()) Das ist einfach eine "überflüssige" Variabelnzuweisung extra, beides (enrollment.isPresent() und "false") sind booleans / warheitswerte und können somit analog zueinander verwendet werden

2023-11-22 17:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EnrollmentConfirmationDialog.java
> +
btw spricht man hier i.d.R von "auskommentieren", weil man dadurch dass man den code zu einem kommentar ändert, ihn "aus dem code heraus nimmt" -> "herauskommentiert" -> "auskommentiert". (Wieder) einkommentieren ist das Gegenteil

2023-11-22 17:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EnrollmentConfirmationDialog.java
> +        String result;
Bei der dekalisatoinierung am besten direkt mit null initialisieren, sollte zwar nicht passieren aber wenn das code generieren innerhalb der schleife mal fehlschlägt versuchst du eine niemals initialisierte variable in Zeile 122 in die entity zu stecken was zu einem systemfehler führen würde

2023-11-22 17:21 UTC, tilokowalski commented on pom.xml
> +            <version>1.18.30</version>
| Geil | Geil | Geil |
|--------|--------|--------|
| Geil | Geil | Geil |
| Geil | Geil | Geil |
| Geil | Geil  | Geil |

2023-11-22 17:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/MainView.java
> +
WIESO HAT REVIEWDOG HIER NICHTS GESAGT ICH HASSE LEERZEILEN (spass)

2023-11-22 17:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EnrollmentConfirmationDialog.java
> +    private EnrollmentEntity enrollmentEntity;
Benennung der Entity Attribute bitte immer ohne Entity

2023-11-22 17:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EnrollmentConfirmationDialog.java
> +            code = enrollmentEntity.getCode();
cool gelöst

2023-11-22 17:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EnrollmentConfirmationDialog.java
> +        H4 codeOutput = new H4(code);
Würde hier vielleicht sogar auf H3 gehen damit das etwas pregnanter ist und man nicht dazu neigt das popup nicht zu lesen weil ja eh nur bisschen random text drin steht. Und dann vielleicht auch inm vaadin blau ("primary" color) wie im Mockup

2023-11-22 17:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EnrollmentConfirmationDialog.java
> +        // TODO Bug: wird zu AllocationPage weitergeleitet, aber in der Navigation ist noch die Startseite ausgewählt
Gerne als @todo an die Methode selbst hier dann nur mit normalem // darauf verweisen das hier vermutlich der bug entsteht. Gilt für alle Todos, lieber mit @todo ins javadoc

2023-11-22 17:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EnrollmentConfirmationDialog.java
> +                UI.getCurrent().navigate("allocation");
könntem mir vorstellen dass der bug dabei entsteht dass du hier auf einen string weiterleitest den du vermutlich aus der @Route der AllocationPage entnommen hast, man kann aber auch generell auf navigatable components weiterleiten mit .navigate(AllocationPage.class) oder so änhlich, siehe mal einen meiner ConfirmDialog Klassen, irgendwo da hatte ich das auch

2023-11-22 17:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EnrollmentConfirmationDialog.java
> +                AllocationPage.frameCodeInput.setVisible(false);
Gut mitgedacht dass du hier direkt dafür sorgen willst, dass man keinen Code mehr eingeben muss, jedoch können wir das nicht so allgemein machen (nach jetzigem stand zwar schon, wird sich aber ändern), da auf der allocation page for einschulungsdatum ja ein hinweistext angezeigt werden soll

2023-11-22 17:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EnrollmentConfirmationDialog.java
> +        final int codeLenght = 6;
Wenn du dem Rat von Herrn Kowalski (siehe unten folgst) könntest du hier sogar die Konstante nutzen -> wiederverwendbarer Code = GEIL

2023-11-22 17:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EnrollmentConfirmationDialog.java
> +        final int codeLenght = 6;
ups siehe oben meinte ich du weisst schon welche stelle gemeint ist

2023-11-22 17:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EnrollmentConfirmationDialog.java
> +        enrollmentEntity.setCode(result);
richtig geile idee von meiner seite aus wäre wenn das ding vielleicht sogar noch tatsächlich gespeichert wird :)

2023-11-22 17:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/AllocationPage.java
> +     *       Can't move a node from one state tree to another. If this is intentional, first remove the node from its current state tree by calling removeFromTree.
ein feiniiiiii. wobei ich das nur aus der konsole kopiert habe

2023-11-22 17:21 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/frame/allocation/CodeInputFrame.java
> +        textFieldCode.setMaxLength(6);
wieder die konstante, omg doppelte wiederverwendung des codes WAHNSINNNNNNNN

2023-11-22 17:23 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EnrollmentConfirmationDialog.java
> +                AllocationPage.frameCodeInput.setVisible(false);
for?????

2023-11-23 07:18 UTC, VogtJoshua submitted a review, later dismissed

2023-11-23 07:36 UTC, VogtJoshua submitted a review, later dismissed

2023-11-23 09:27 UTC, lenav99 approved these changes

2023-11-23 12:31 UTC, tilokowalski requested changes

2023-11-23 12:31 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/data/entity/enrollment/EnrollmentEntity.java
> +    public static final int codeLength = 6;
KOSTANTEN_SCHREIBT_MAN_GROSS

2023-11-23 12:31 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/data/entity/enrollment/EnrollmentEntity.java
> +    public static final int codeLength = 6;
und ganz oben in die klasse

2023-11-23 12:31 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EnrollmentConfirmationDialog.java
> +                UI.getCurrent().navigate("allocation");
über die klasse zu gehen ist trotzdem besser, falls wir die route nochmal ändern sollten

2023-11-23 12:31 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/frame/allocation/CodeInputFrame.java
> +        textFieldCode.setMaxLength(EnrollmentEntity.codeLength);
Hier wirst du dann die konstante anpassen müssen

2023-11-23 12:39 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/frame/codeInputFrame/CodeInputFrame.java
> +package com.fes.hazelnut.schoolnut.view.page.frame.codeInputFrame;
⚠️ **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.naming.PackageNameCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Package name 'com.fes.hazelnut.schoolnut.view.page.frame.codeInputFrame' must match pattern '^[a-z]+(\.[a-z][a-z0-9]*)*$'.

2023-11-23 12:39 UTC, lenav99 approved these changes

2023-11-23 12:42 UTC, tilokowalski approved these changes

2023-11-23 12:42 UTC, VogtJoshua approved these changes

2023-11-23 12:42 UTC, merged