Feature im 07 2 code eingabe Dialog
fes-wiesbaden/22be10-p3-fesus-gruppe1 pull request #44
Opened 2023-11-25 14:18 UTC by thisami

@VogtJoshua ich habe den Button auf die EnrollmentPage gepackt, du musst ihn dann nur noch an die richtige Stelle packen. Die statische EnrollmentEtity setze ich auf der EnrollmentPage aus dem zugehörigen Code. 
Solltest den Button aber umbenennen.

2023-11-25 15:30 UTC, VogtJoshua commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/AllocationPage.java
> +     * @todo Doc ändern.
Ist das gewollt, soll das mit in develop?

2023-11-25 15:31 UTC, VogtJoshua submitted a review, later dismissed

2023-11-25 20:44 UTC, lenav99 approved these changes

2023-11-25 20:44 UTC, lenav99 commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EditDialog.java
> +            new H1("Einschulung bearbeiten"),
bin mir nicht sicher, aber hatten wir uns nicht auf H2 geeinigt?

2023-11-25 21:01 UTC, thisami commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/AllocationPage.java
> +     * @todo Doc ändern.
Ne, ändere ich gleich, danke!

2023-11-25 21:01 UTC, thisami commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EditDialog.java
> +            new H1("Einschulung bearbeiten"),
Da habe ich mich an dem ConfirmationDialog von Tilo orientiert

2023-11-26 08:10 UTC, VogtJoshua submitted a review, later dismissed

2023-11-26 16:38 UTC, lenav99 submitted a review, later dismissed

2023-11-27 10:50 UTC, tilokowalski requested changes

2023-11-27 10:50 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EditDialog.java
> +
resizable und draggable einstellung wäre noch gut, analog zu den anderen dialogen

2023-11-27 10:50 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EditDialog.java
> +        addClassName(LumoUtility.Padding.XLARGE);
Die Dialoge sollten auch kein zusätzliches Padding haben, das gibt es nur in den Pages

2023-11-27 10:50 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EditDialog.java
> +        EnrollmentEntity enrollmentEntity = enrollment.get();
Benennung enrollment wäre besser

2023-11-27 10:50 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EditDialog.java
> +        Optional<EnrollmentEntity> enrollment = enrollmentService.findOneByCode(textFieldCode.getValue());
Benennung enrollmentOptional oder so ähnlich wäre besser, es handelt sich an dieser Stelle nämlich (noch) nicht um eine tatsächliche entity sondern nur um das optional object

2023-11-27 12:19 UTC, VogtJoshua approved these changes

2023-11-27 14:18 UTC, VogtJoshua approved these changes

2023-11-27 14:31 UTC, lenav99 approved these changes

2023-11-27 16:30 UTC, thisami commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EditDialog.java
> +        EnrollmentEntity enrollmentEntity = enrollment.get();
Da gibt es schon ein enrollment, deswegen habe ich es enrollmentEntity genannt

2023-11-27 16:31 UTC, thisami commented on src/main/java/com/fes/hazelnut/schoolnut/view/component/dialog/enrollment/EditDialog.java
> +        Optional<EnrollmentEntity> enrollment = enrollmentService.findOneByCode(textFieldCode.getValue());
Ignorier den anderen Kommentar

2023-11-28 08:34 UTC, merged