Enrollment PDF Styling
fes-wiesbaden/22be10-p3-fesus-gruppe1 pull request #46
Opened 2023-11-26 16:46 UTC by lenav99

Schaut mal ob das so alles passt. Danke

2023-11-26 16:46 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/document/pdf/EnrollmentFormDocument.java
> +        PdfPTable tableFirm = createFirmTable();
⚠️ **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.coding.VariableDeclarationUsageDistanceCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Distance between variable 'tableFirm' declaration and its first usage is 9, but allowed 8.  Consider making that variable final if you still need to store its value in advance (before method calls that might have side effects on the original value).

2023-11-26 16:46 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/document/pdf/EnrollmentFormDocument.java
> +        PdfPTable tableContact = createContactTable();
⚠️ **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.coding.VariableDeclarationUsageDistanceCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Distance between variable 'tableContact' declaration and its first usage is 11, but allowed 8.  Consider making that variable final if you still need to store its value in advance (before method calls that might have side effects on the original value).

2023-11-26 16:46 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/document/pdf/EnrollmentFormDocument.java
> +        Paragraph headerContact = new Paragraph("Gesetzlicher Vertreter / Nächster Angehöriger", FONT_TITLE);
⚠️ **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.coding.VariableDeclarationUsageDistanceCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Distance between variable 'headerContact' declaration and its first usage is 10, but allowed 8.  Consider making that variable final if you still need to store its value in advance (before method calls that might have side effects on the original value).

2023-11-26 16:46 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/document/pdf/EnrollmentFormDocument.java
> +     * @return The contact table.
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.javadoc.RequireEmptyLineBeforeBlockTagGroupCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Javadoc tag '@return' should be preceded with an empty line.

2023-11-26 16:46 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/document/pdf/EnrollmentFormDocument.java
> +     * @return The firm table.
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.javadoc.RequireEmptyLineBeforeBlockTagGroupCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Javadoc tag '@return' should be preceded with an empty line.

2023-11-26 16:46 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/document/pdf/EnrollmentFormDocument.java
> +     * @return The education table.
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.javadoc.RequireEmptyLineBeforeBlockTagGroupCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Javadoc tag '@return' should be preceded with an empty line.

2023-11-26 16:46 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/document/pdf/EnrollmentFormDocument.java
> +     * @return The student table.
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.javadoc.RequireEmptyLineBeforeBlockTagGroupCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Javadoc tag '@return' should be preceded with an empty line.

2023-11-26 16:46 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/document/pdf/EnrollmentFormDocument.java
> +    private PdfPTable createStudentTable() {
⚠️ **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.sizes.MethodLengthCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Method createStudentTable length is 63 lines (max allowed is 60).

2023-11-26 16:46 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/document/pdf/EnrollmentFormDocument.java
> +            addTableCell(table, addressOld.getZip() + ", " + addressOld.getCity() + ", " +
⚠️ **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.whitespace.OperatorWrapCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>'+' should be on a new line.

2023-11-26 16:46 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/document/pdf/EnrollmentFormDocument.java
> +     * @return The enrollment paragraph.
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.javadoc.RequireEmptyLineBeforeBlockTagGroupCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Javadoc tag '@return' should be preceded with an empty line.

2023-11-26 16:46 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/document/pdf/EnrollmentFormDocument.java
> +     * @param gender The gender of the enrolled student.
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.javadoc.RequireEmptyLineBeforeBlockTagGroupCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Javadoc tag '@param' should be preceded with an empty line.

2023-11-26 20:47 UTC, thisami approved these changes

2023-11-26 20:47 UTC, thisami commented on src/main/java/com/fes/hazelnut/schoolnut/document/pdf/EnrollmentFormDocument.java
> + * provides a concatinated version of all enrollment forms in the class.
Du hast den Formatter noch drin 😆

2023-11-27 10:54 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/document/pdf/EnrollmentFormDocument.java
> +     * @param table The table to add the cell to.
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.javadoc.RequireEmptyLineBeforeBlockTagGroupCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Javadoc tag '@param' should be preceded with an empty line.

2023-11-27 10:54 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/data/Gender.java
> +    public String getTitle() {
⚠️ **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.javadoc.MissingJavadocMethodCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing a Javadoc comment.

2023-11-27 10:57 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/data/Gender.java
> +     * @return The german name of the enum constant.
🚫 **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.javadoc.RequireEmptyLineBeforeBlockTagGroupCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Javadoc tag '@return' should be preceded with an empty line.

2023-11-27 12:09 UTC, tilokowalski requested changes
Zum Formatting thema siehe Whatsapp, ansonsten nur ein paar kleinigkeiten

2023-11-27 12:09 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/document/pdf/EnrollmentFormDocument.java
> +        PdfPTable tableSpacing = new PdfPTable(1);
spacing tables als hilfestellung brauchst du nicht, du kannst stattdessen setSpacingBefore und setSpacingAfter bei den anderen Elementen nutzen.

Schätze du hast das vom title in der document vorlage abgeguckt, da ging es nicht anders weil spacing before und after nicht für das aller erste dokument auf der seite funktionieren

2023-11-27 13:24 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/data/entity/address/AddressEntity.java
> +     /**
⚠️ **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.indentation.CommentsIndentationCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Block comment has incorrect indentation level 5, expected is 4, indentation should be the same level as line 56.

2023-11-27 14:20 UTC, VogtJoshua approved these changes

2023-11-27 19:45 UTC, thisami submitted a review, later dismissed

2023-11-27 21:38 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/document/pdf/EnrollmentFormDocument.java
> +    private PdfPTable createSectionStudent() {
⚠️ **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.sizes.MethodLengthCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Method createSectionStudent length is 67 lines (max allowed is 60).

2023-11-27 21:38 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +import lombok.extern.slf4j.Slf4j;
⚠️ **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Extra separation in import group before 'lombok.extern.slf4j.Slf4j'

2023-11-27 22:24 UTC, tilokowalski approved these changes

2023-11-28 07:44 UTC, VogtJoshua submitted a review, later dismissed

2023-11-28 08:09 UTC, thisami approved these changes

2023-11-28 09:18 UTC, merged