Feature/im 07 03 einschulungsformular
fes-wiesbaden/22be10-p3-fesus-gruppe1 pull request #47
Opened 2023-11-27 16:02 UTC by VogtJoshua

Ist in Arbeit.

Es fehlt die Speicherung und die Logik zum laden einer Enrollmentform.

Ich weiß nicht ob ich noch dazu komme. :(

2023-11-27 22:18 UTC, tilokowalski requested changes

2023-11-27 22:18 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +    Binder<AddressEntity> binderAddressRepresentativePerson = new Binder<>(AddressEntity.class);
"binderAddressRepresentative" wäre sprechend genug und passt zum Rest des Codes wo wir die addresse des erziehungsberechtigten nutzen, dann muss es nicht ganz so lang sein (ist bei dieser Klasse wegen der vielen Elemente halt kaum vermeidbar also abgesehen hiervon schon okay so)

2023-11-27 22:18 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +    private final TextField textFieldApprenticeship = new TextField("Ausbildungsberuf");
Korrekt. Beim, bzw. vor dem Speichern muss dann noch jeweils geprüft werden ob die Felder gefüllt sind, bzw. kannst du, wenn du den Binder überall richtig gesetzt hast, vor dem speichern auch schon überprüfen ob die pflicht Attribute nicht null sind

2023-11-27 22:18 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +    private final TextField textFieldApprenticeship = new TextField("Ausbildungsberuf");
Falls dann etwas unzureichend ausgefüllt wurde natürlich keinen Speicherungsversuch und toast notification anzeigen, siehe diverse beispiele bei formfeldern

2023-11-27 22:18 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +
ein leerzeichen zu viel

2023-11-27 22:18 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +    /**
fehlende leerzeile

2023-11-27 22:18 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +
leerzeile zu viel

2023-11-27 22:18 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +     * The textFieldApprenticeship represents the apprentice of the student.
Wieso soll das ein TextField sein? Wir haben doch eine ApprenticeshipEntity, da wäre doch eine ComboBox besser.

Ich würde in diesem Fall aber nur die ComboBox für die specialization behalten und den Titel zu "Ausbildungsberuf" ändern, da die anzeige in unserer specialization kombobox ja immer die methode nutzen sollte, die Ausbildungsberuf und Fachrichtung vereint (ggf. Standard weglässt wenn nur eine da, usw.). So haben wir es auch überallsonst gemacht,

Also nochmal in kurz.

- Statt getrenntem Ausbildungsberuf und Fachrichtung nur eine SpecializationCombobox
- Für die Anzeige die custom title methode die auch den Ausbildungsberuf mit anzeigt nutzen
- Da dann durch den binder keine apprenticeship gesetzt werden kann, muss vor der speicherung noch manuell die apprenticehip gesetzt werden (auf die, die zur fachrichtung gehört)

2023-11-27 22:18 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +     * @todo DropDown mit Werten füllen
Wäre jedoch sehr wichtig :D

2023-11-27 22:18 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +        //comboBoxSpecialization.setItems(SpecializationEntity.;
das ist kein Enum sondern eine unserer entitites, du musst dir also alle davon in eine liste bzw ein set laden und dieses hier als items setzen. Das machst du über den zugehörigen Service. In der Klassenverwaltung haben wir auch schon eine combobox für specializations, da kannst du es dir angucken falls es hilft

2023-11-27 22:18 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +        comboBoxSpecialization.setItemLabelGenerator(SpecializationEntity::getTitle);
Als Ergänzung zum Kommentar weiter oben, Thematik Apprenticeship TextField, zusammengesetzte Kombobox usw:

Hier dann die custom title methode verwernden: getTitleWithApprenticeship

2023-11-27 22:18 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +    private final ComboBox<Degree> comboBoxDiploma = new ComboBox<>("Höchster erreichter Abschluss");
Du musst mitu den Benennungen deiner Variablen nicht immer das rad nicht immer neu erfinden :D Wir nennen das im ganzen project "Degree" und nicht diploma

2023-11-27 22:18 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +     * sets the page.
Sehr ungenaues javadoc und sehr ungenaue param description

2023-11-27 22:18 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +     * currentEnrollment represents the current enrollment.
das javadoc braucht nicht am Anfang den namen der variable enthalten. Ich würde hier einfach schreiben.

The current enrollment to be edited (oder so ähnlich)

Betrifft eigentlich nahezu jedes deiner Kommentare, außerdem sollten wir die Beschreibungen und auch die der einzelnen tags wie z.B. @param immer mit Großbuchstaben anfangen, daraus ergibt sich dass hier nicht der Variabeln name stehen darf

2023-11-27 22:18 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +        H1 frameTitle = new H1("Schüler/ Schülerin");
"Schüler / Schülerin" oder "Schüler/in"

2023-11-27 22:18 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +     * @return result
Beschreibung

2023-11-27 22:18 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +     * @return result
Beschreibung

2023-11-27 22:18 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +     * @return result
Beschreibung

2023-11-27 22:20 UTC, tilokowalski commented
Zu draft gemacht weil Feature unvollständig. 

Branch hat Priorität weil #45 davon abhängig ist

2023-11-28 15:47 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/data/entity/address/AddressEntity.java
> +import com.vaadin.flow.internal.StringUtil;
⚠️ **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Wrong lexicographical order for 'com.vaadin.flow.internal.StringUtil' import. Should be before 'org.apache.commons.lang3.StringUtils'.

2023-11-28 15:51 UTC, tilokowalski submitted a review, later dismissed

2023-11-28 16:45 UTC, tilokowalski commented
Fertig implementiert, + neu gestylet und angeordnet + dsgvo logik aus anderer story übernommen

2023-11-28 19:18 UTC, thisami requested changes

2023-11-28 19:18 UTC, thisami commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +    private final DatePicker dateImmigration = new DatePicker("Datum des Zugugs nach Deutschland");
Datum des "Zuzugs" nicht "Zugugs"

2023-11-28 19:18 UTC, thisami commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +            new Text("Als minderjährige Person benötigen wir die Einwilligung eines gesetzlichen Vertreters. Bitte drucken Sie die Datenschutzerklärung aus und lassen Sie sie von Ihrem gesetzlichen V
"Sie sie" hört sich irgendwie merkwürdig an

2023-11-28 19:18 UTC, thisami commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +            new Text("Als minderjährige Person benötigen wir die Einwilligung eines gesetzlichen Vertreters. Bitte drucken Sie die Datenschutzerklärung aus und lassen Sie sie von Ihrem gesetzlichen V
vielleicht "Sie diese"

2023-11-28 20:35 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/allocation/TeacherPage.java
> +import lombok.Setter;
⚠️ **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Extra separation in import group before 'lombok.Setter'

2023-11-28 20:35 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +    @Override
⚠️ **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.javadoc.MissingJavadocMethodCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Missing a Javadoc comment.

2023-11-28 20:35 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +    public VerticalLayout createSectionThree() {
⚠️ **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.sizes.MethodLengthCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Method createSectionThree length is 66 lines (max allowed is 60).

2023-11-28 22:56 UTC, closed without merging