Feature IM-07-03 (Einschulungsformular)
fes-wiesbaden/22be10-p3-fesus-gruppe1 pull request #49
Opened 2023-11-28 22:56 UTC by tilokowalski

2023-11-28 22:56 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +    public VerticalLayout createSectionThree() {
⚠️ **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.sizes.MethodLengthCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Method createSectionThree length is 62 lines (max allowed is 60).

2023-11-28 22:59 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +    public VerticalLayout createSectionThree() {
Wäre in diesem Fall unsinnig, das zu ändern

2023-11-29 07:34 UTC, thisami commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +    private final DatePicker dateImmigration = new DatePicker("Datum des Zugugs nach Deutschland");
Zuzug

2023-11-29 08:36 UTC, lenav99 submitted a review, later dismissed

2023-11-29 08:51 UTC, VogtJoshua submitted a review, later dismissed

2023-11-29 08:53 UTC, thisami requested changes

2023-11-29 08:53 UTC, thisami commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +     * Number of the address of the company of the apprentice.
Number hört sich irgendwie merkwürdig an

2023-11-29 08:53 UTC, thisami commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +            titleAddressOld, new Text("Bitte nur ausfüllen, wenn sich die Anschrift innerhalb der letzten 3 Jahre geändert hat!"),
Evtl "sich ihre"

2023-11-29 08:53 UTC, thisami commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/EnrollmentPage.java
> +            new Text("Als minderjährige Person benötigen Sie eine Einwilligung zur Datenschutzerklärung von einem gesetzlichen Vertreters. Bitte drucken Sie die Datenschutzerklärung aus und lassen Si
Statt "Sie sie", evtl "Sie diese"

2023-11-29 09:11 UTC, lenav99 approved these changes

2023-11-29 09:15 UTC, VogtJoshua approved these changes

2023-11-29 09:16 UTC, merged