Feature/todo finished some todos
fes-wiesbaden/22be10-p3-fesus-gruppe1 pull request #55
Opened 2023-11-29 19:36 UTC by thisami

2023-11-29 20:07 UTC, tilokowalski requested changes

2023-11-29 20:07 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/page/allocation/StudentPage.java
> +        setWidth("600px");
setWidthFull() + setMaxWidth(600, Unit.PIXELS) wäre besser, für wenn der Viewport tatäschlich mal kleiner als 600px ist (z.B. am Handy).

Dann wäre es immer so breit wie möglich, höchstens jedoch 600px. Jetzt enforcet du immer 600 und man müsste seitlich scrollen am Handy

2023-11-30 06:35 UTC, lenav99 submitted a review, later dismissed

2023-11-30 06:37 UTC, VogtJoshua approved these changes

2023-11-30 07:01 UTC, VogtJoshua submitted a review, later dismissed

2023-11-30 07:01 UTC, lenav99 submitted a review, later dismissed

2023-11-30 07:04 UTC, VogtJoshua approved these changes

2023-11-30 07:04 UTC, lenav99 approved these changes

2023-11-30 07:09 UTC, tilokowalski approved these changes

2023-11-30 07:09 UTC, merged