Change from drawer layout to navbar layout
fes-wiesbaden/22be10-p3-fesus-gruppe1 pull request #58
Opened 2023-11-30 09:53 UTC by tilokowalski

2023-11-30 09:54 UTC, thisami requested changes
Nö, approve ich nicht

2023-11-30 16:35 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/MainView.java
> +import com.fes.hazelnut.schoolnut.helper.ServiceHelper;
⚠️ **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Extra separation in import group before 'com.fes.hazelnut.schoolnut.helper.ServiceHelper'

2023-11-30 16:35 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/MainView.java
> +import com.fes.hazelnut.schoolnut.helper.ServiceHelper;
⚠️ **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Wrong lexicographical order for 'com.fes.hazelnut.schoolnut.helper.ServiceHelper' import. Should be before 'java.util.concurrent.CompletableFuture'.

2023-11-30 16:35 UTC, tilokowalski commented on src/main/java/com/fes/hazelnut/schoolnut/view/MainView.java
> +import com.fes.hazelnut.schoolnut.helper.session.NavigationHelper;
⚠️ **[checkstyle]** <com.puppycrawl.tools.checkstyle.checks.imports.CustomImportOrderCheck> <sub>reported by [reviewdog](https://github.com/reviewdog/reviewdog) :dog:</sub><br>Wrong lexicographical order for 'com.fes.hazelnut.schoolnut.helper.session.NavigationHelper' import. Should be before 'java.util.concurrent.CompletableFuture'.

2023-11-30 17:04 UTC, thisami approved these changes

2023-11-30 19:41 UTC, lenav99 approved these changes

2023-12-01 06:35 UTC, thisami approved these changes

2023-12-01 06:37 UTC, merged